# Generated by Django 6.0.5 on 2026-05-06 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GEOSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=20, unique=True)),
                ('title', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('gds_type', models.CharField(blank=True, max_length=100)),
                ('taxon', models.CharField(blank=True, max_length=100)),
                ('platform_id', models.CharField(blank=True, max_length=20)),
                ('n_samples', models.IntegerField(default=0)),
                ('publication_date', models.CharField(blank=True, max_length=10)),
                ('supplementary', models.CharField(blank=True, max_length=200)),
                ('ftp_link', models.URLField(blank=True, max_length=300)),
                ('bioproject', models.CharField(blank=True, max_length=30)),
                ('platform_title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'geo_series',
            },
        ),
        migrations.CreateModel(
            name='TCGACase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=50, unique=True)),
                ('primary_site', models.CharField(blank=True, max_length=100)),
                ('disease_type', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('age_at_index', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tcga_case',
            },
        ),
        migrations.CreateModel(
            name='TCGAProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=50, unique=True)),
                ('name', models.TextField()),
                ('disease_type', models.JSONField(default=list)),
                ('primary_site', models.JSONField(default=list)),
                ('case_count', models.IntegerField(default=0)),
                ('file_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tcga_project',
            },
        ),
        migrations.CreateModel(
            name='GEOSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsm_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('organism', models.CharField(blank=True, max_length=100)),
                ('platform_id', models.CharField(blank=True, max_length=20)),
                ('clinical_metadata', models.JSONField(blank=True, default=dict)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.geoseries')),
            ],
            options={
                'db_table': 'geo_sample',
            },
        ),
        migrations.CreateModel(
            name='HGNCGene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgnc_id', models.CharField(max_length=20, unique=True)),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('name', models.TextField(blank=True)),
                ('locus_group', models.CharField(blank=True, max_length=100)),
                ('locus_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('entrez_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('ensembl_gene_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('refseq_accession', models.CharField(blank=True, max_length=50)),
                ('uniprot_ids', models.CharField(blank=True, max_length=100)),
                ('alias_symbol', models.TextField(blank=True)),
                ('prev_symbol', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'hgnc_gene',
                'indexes': [models.Index(fields=['symbol'], name='hgnc_gene_symbol_bd6301_idx'), models.Index(fields=['ensembl_gene_id'], name='hgnc_gene_ensembl_386dc1_idx'), models.Index(fields=['entrez_id'], name='hgnc_gene_entrez__73cf55_idx')],
            },
        ),
        migrations.CreateModel(
            name='TCGAFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=50, unique=True)),
                ('file_name', models.CharField(max_length=300)),
                ('data_type', models.CharField(blank=True, max_length=100)),
                ('experimental_strategy', models.CharField(blank=True, max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('local_path', models.CharField(blank=True, max_length=500)),
                ('cases', models.ManyToManyField(blank=True, related_name='files', to='core.tcgacase')),
            ],
            options={
                'db_table': 'tcga_file',
            },
        ),
        migrations.AddField(
            model_name='tcgacase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='core.tcgaproject', to_field='project_id'),
        ),
    ]
