# Generated by Django 6.0.5 on 2026-05-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("downloading", "Downloading"),
                            ("downloaded", "Downloaded"),
                            ("parsed", "Parsed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("downloaded_bytes", models.BigIntegerField(default=0)),
                ("local_path", models.CharField(blank=True, max_length=500)),
                ("parser_used", models.CharField(blank=True, max_length=100)),
                ("parse_summary", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tcga_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_status",
                        to="core.tcgafile",
                    ),
                ),
            ],
            options={
                "db_table": "download_status",
                "indexes": [
                    models.Index(fields=["status"], name="download_st_status_0fcd35_idx"),
                    models.Index(fields=["updated_at"], name="download_st_updated_ec2119_idx"),
                ],
            },
        ),
    ]
