# Generated by Django 6.0.5 on 2026-05-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_downloadstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="TCGAExpressionRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("gene_id", models.CharField(blank=True, db_index=True, max_length=40)),
                ("gene_id_versionless", models.CharField(blank=True, db_index=True, max_length=30)),
                ("gene_name", models.CharField(blank=True, db_index=True, max_length=120)),
                ("gene_type", models.CharField(blank=True, max_length=120)),
                ("unstranded", models.FloatField(blank=True, null=True)),
                ("stranded_first", models.FloatField(blank=True, null=True)),
                ("stranded_second", models.FloatField(blank=True, null=True)),
                ("tpm_unstranded", models.FloatField(blank=True, null=True)),
                ("fpkm_unstranded", models.FloatField(blank=True, null=True)),
                ("fpkm_uq_unstranded", models.FloatField(blank=True, null=True)),
                ("raw_row", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hgnc_gene",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tcga_expression_records", to="core.hgncgene"),
                ),
                (
                    "tcga_file",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="expression_records", to="core.tcgafile"),
                ),
            ],
            options={
                "db_table": "tcga_expression_record",
                "indexes": [
                    models.Index(fields=["gene_id"], name="tcga_expres_gene_id_2f58cb_idx"),
                    models.Index(fields=["gene_id_versionless"], name="tcga_expres_gene_id_87dd2f_idx"),
                    models.Index(fields=["gene_name"], name="tcga_expres_gene_na_70935c_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TCGAMutation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hugo_symbol", models.CharField(blank=True, db_index=True, max_length=50)),
                ("entrez_gene_id", models.CharField(blank=True, db_index=True, max_length=20)),
                ("variant_classification", models.CharField(blank=True, db_index=True, max_length=80)),
                ("variant_type", models.CharField(blank=True, max_length=40)),
                ("chromosome", models.CharField(blank=True, max_length=20)),
                ("start_position", models.BigIntegerField(blank=True, null=True)),
                ("end_position", models.BigIntegerField(blank=True, null=True)),
                ("reference_allele", models.CharField(blank=True, max_length=200)),
                ("tumor_seq_allele2", models.CharField(blank=True, max_length=200)),
                ("tumor_sample_barcode", models.CharField(blank=True, db_index=True, max_length=80)),
                ("raw_row", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hgnc_gene",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tcga_mutations", to="core.hgncgene"),
                ),
                (
                    "tcga_file",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mutations", to="core.tcgafile"),
                ),
            ],
            options={
                "db_table": "tcga_mutation",
                "indexes": [
                    models.Index(fields=["hugo_symbol"], name="tcga_mutati_hugo_sy_43514d_idx"),
                    models.Index(fields=["entrez_gene_id"], name="tcga_mutati_entrez__a017f9_idx"),
                    models.Index(fields=["variant_classification"], name="tcga_mutati_variant_e6f16e_idx"),
                ],
            },
        ),
    ]
