# Generated by Django 6.0.5 on 2026-06-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tcga_parsed_tables'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='downloadstatus',
            new_name='download_st_status_7b2161_idx',
            old_name='download_st_status_0fcd35_idx',
        ),
        migrations.RenameIndex(
            model_name='downloadstatus',
            new_name='download_st_updated_549998_idx',
            old_name='download_st_updated_ec2119_idx',
        ),
        migrations.RenameIndex(
            model_name='tcgaexpressionrecord',
            new_name='tcga_expres_gene_id_09efeb_idx',
            old_name='tcga_expres_gene_id_2f58cb_idx',
        ),
        migrations.RenameIndex(
            model_name='tcgaexpressionrecord',
            new_name='tcga_expres_gene_id_eede97_idx',
            old_name='tcga_expres_gene_id_87dd2f_idx',
        ),
        migrations.RenameIndex(
            model_name='tcgaexpressionrecord',
            new_name='tcga_expres_gene_na_6790c4_idx',
            old_name='tcga_expres_gene_na_70935c_idx',
        ),
        migrations.RenameIndex(
            model_name='tcgamutation',
            new_name='tcga_mutati_hugo_sy_03e318_idx',
            old_name='tcga_mutati_hugo_sy_43514d_idx',
        ),
        migrations.RenameIndex(
            model_name='tcgamutation',
            new_name='tcga_mutati_entrez__a63a5e_idx',
            old_name='tcga_mutati_entrez__a017f9_idx',
        ),
        migrations.RenameIndex(
            model_name='tcgamutation',
            new_name='tcga_mutati_variant_97af36_idx',
            old_name='tcga_mutati_variant_e6f16e_idx',
        ),
        migrations.AddField(
            model_name='tcgacase',
            name='molecular_subtype',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
