# Generated by Django 6.0.5 on 2026-06-14 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_molecular_subtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('algorithm', models.CharField(max_length=80)),
                ('n_samples', models.IntegerField(default=0)),
                ('n_features', models.IntegerField(default=0)),
                ('test_size', models.FloatField(default=0.2)),
                ('random_state', models.IntegerField(default=42)),
                ('hyperparams', models.JSONField(blank=True, default=dict)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('f1_macro', models.FloatField(blank=True, null=True)),
                ('f1_weighted', models.FloatField(blank=True, null=True)),
                ('confusion_matrix', models.JSONField(blank=True, default=list)),
                ('class_labels', models.JSONField(blank=True, default=list)),
                ('classification_report', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ml_model_run',
                'ordering': ['-run_date'],
            },
        ),
        migrations.AddField(
            model_name='tcgacase',
            name='predicted_subtype',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='MLGeneImportance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(db_index=True, max_length=120)),
                ('gene_id', models.CharField(blank=True, max_length=40)),
                ('importance', models.FloatField()),
                ('rank', models.IntegerField()),
                ('hgnc_gene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hgncgene')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene_importances', to='core.mlmodelrun')),
            ],
            options={
                'db_table': 'ml_gene_importance',
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['run', 'rank'], name='ml_gene_imp_run_id_1638b3_idx'), models.Index(fields=['gene_name'], name='ml_gene_imp_gene_na_99e110_idx')],
            },
        ),
    ]
